'use strict';

// response-cache.js — caches /v1/responses by response ID so the proxy can
// reconstruct conversation history when a client (e.g. Codex with
// requires_openai_auth=true) sends previous_response_id instead of replaying
// the full conversation in input[].
//
// Ollama's /v1/responses endpoint is stateless — it ignores
// previous_response_id.  This module lets the proxy emulate the stateful
// behaviour Codex expects: store each completed response, then when a
// follow-up request arrives with previous_response_id and a minimal input[],
// prepend the stored conversation items so Ollama sees the full history.

const fs = require('fs');
const path = require('path');

// In-memory store: responseId -> { output: [...], model: string, storedAt: number }
const store = new Map();

// Maximum entries to prevent unbounded growth.  Codex conversations rarely
// exceed a few hundred turns; 1000 is a safe ceiling.
const MAX_ENTRIES = 1000;

/**
 * Store a completed response keyed by its `id`.
 * Only the `output` array and `model` are kept — everything else is
 * either regenerated by the proxy or irrelevant for history reconstruction.
 */
function remember(response) {
  if (!response || typeof response !== 'object') return;
  const id = response.id;
  if (!id || typeof id !== 'string') return;
  const output = Array.isArray(response.output) ? response.output : [];
  // Deep-copy so later mutations of the response object don't corrupt the cache.
  store.set(id, {
    output: JSON.parse(JSON.stringify(output)),
    model: response.model || null,
    storedAt: Date.now(),
  });
  // Evict oldest entries if over the limit.
  if (store.size > MAX_ENTRIES) {
    const oldest = [...store.entries()]
      .sort((a, b) => a[1].storedAt - b[1].storedAt)
      .slice(0, store.size - MAX_ENTRIES);
    for (const [key] of oldest) store.delete(key);
  }
}

/**
 * Retrieve the stored output items for a given response ID.
 * Returns an array of output items (may be empty).
 */
function recall(responseId) {
  if (!responseId || typeof responseId !== 'string') return null;
  const entry = store.get(responseId);
  if (!entry) return null;
  return entry.output;
}

/**
 * Reconstruct the full conversation history from a chain of
 * previous_response_id values.
 *
 * Codex sends previous_response_id pointing to the *immediately preceding*
 * response.  Each stored response may itself have been built on an earlier
 * one, but since Codex replays the full input[] on every turn when it's
 * *not* using previous_response_id, we only need to resolve one level:
 * the stored output from the single previous_response_id.
 *
 * If the caller already included conversation items in input[] (detected by
 * the presence of any assistant message or function_call/function_call_output
 * items), we assume the client is already replaying history and return null.
 *
 * @param {object} body - The parsed request body.
 * @returns {array|null} - Array of input items to prepend, or null if no
 *   reconstruction is needed/possible.
 */
function reconstructHistory(body) {
  if (!body || typeof body !== 'object') return null;
  const prevId = body.previous_response_id;
  if (!prevId || typeof prevId !== 'string') return null;

  const input = Array.isArray(body.input) ? body.input : [];

  // Detect whether the client already sent conversation history.
  // If input[] contains any assistant messages, function_calls, or
  // function_call_outputs, the client is replaying history itself.
  const hasHistory = input.some((item) => {
    if (!item || typeof item !== 'object') return false;
    if (item.role === 'assistant') return true;
    if (item.type === 'function_call') return true;
    if (item.type === 'function_call_output') return true;
    if (item.type === 'custom_tool_call') return true;
    if (item.type === 'custom_tool_call_output') return true;
    if (item.type === 'reasoning') return true;
    if (item.type === 'web_search_call') return true;
    if (item.type === 'web_search_output') return true;
    if (item.type === 'tool_search_call') return true;
    if (item.type === 'tool_search_output') return true;
    if (item.type === 'image_generation_call') return true;
    return false;
  });

  if (hasHistory) return null; // Client already replaying history; nothing to do.

  const storedOutput = recall(prevId);
  if (!storedOutput || storedOutput.length === 0) return null;

  // Convert the stored response output items into input-format items.
  // Most output items can be passed through as-is because the Responses
  // API accepts the same item types in both input[] and output[].
  // We do NOT include reasoning items in the reconstructed history because
  // Ollama models can get confused by reasoning summaries from prior turns
  // and may treat them as new instructions.  The assistant messages and
  // function calls/outputs are the meaningful conversation history.
  const historyItems = storedOutput.filter((item) => {
    if (!item || typeof item !== 'object') return false;
    // Skip reasoning items — they're internal to each turn.
    if (item.type === 'reasoning') return false;
    return true;
  });

  if (historyItems.length === 0) return null;
  return historyItems;
}

/**
 * Clear all cached responses (for testing).
 */
function clear() {
  store.clear();
}

/**
 * Return the current cache size (for testing/debugging).
 */
function size() {
  return store.size;
}

module.exports = {
  remember,
  recall,
  reconstructHistory,
  clear,
  size,
};
